### PR TITLE
Added onNoResult callback to GooglePlacesSuggest

### PR DESCRIPTION
**Pull request by nmiddendorff**
- Added an optional `onNoResult` callback function which is called when no results are found upon hitting enter. 
- Added example `onNoResult` callback to the ReadMe.

no-results-callback

Feature for #35

### CODE REVIEW

**Comment by nmiddendorff** [comment]
This is not ready yet. brb

**Comment by nmiddendorff** [comment]
This should be ready to go now!

**Comment by xuopled** [comment]
Thank you @nmiddendorff for your work

**Comment by xuopled** [comment]
I just published `v3.6.0`

**Pull request merged**
